import { z } from "zod";
import { Student } from "@/components/StudentsTable/columns";
import { adjustDate } from "./utils";

export const dummyStudents: Student[] = [
	{
		id: "1",
		fullName: "John Doe",
		email: "john.doe@example.com",
		phoneNumber: "+1234567890",
		instance: "University of Technology",
		password: "password123",
		createdAt: adjustDate(new Date(), 7),
	},
	{
		id: "2",
		fullName: "Jane Smith",
		email: "jane.smith@example.com",
		phoneNumber: "+1987654321",
		instance: "State College",
		password: "securepass456",
		createdAt: adjustDate(new Date(), 2),
	},
	{
		id: "3",
		fullName: "Alex Johnson",
		email: "alex.johnson@example.com",
		phoneNumber: "+1122334455",
		instance: "Tech Institute",
		password: "alexpass789",
		createdAt: adjustDate(new Date(), 4),
	},
	{
		id: "4",
		fullName: "Emily Brown",
		email: "emily.brown@example.com",
		phoneNumber: "+1555666777",
		instance: "Community College",
		password: "emilyb2023",
		createdAt: adjustDate(new Date(), 5),
	},
	{
		id: "5",
		fullName: "Michael Lee",
		email: "michael.lee@example.com",
		phoneNumber: "+1999888777",
		instance: "Engineering School",
		password: "mikelee321",
		createdAt: adjustDate(new Date(), 9),
	},
	{
		id: "6",
		fullName: "Sarah Wilson",
		email: "sarah.wilson@example.com",
		phoneNumber: "+1222333444",
		instance: "Liberal Arts College",
		password: "wilsonsarah1",
		createdAt: adjustDate(new Date(), -2),
	},
	{
		id: "7",
		fullName: "David Taylor",
		email: "david.taylor@example.com",
		phoneNumber: "+1777888999",
		instance: "Business School",
		password: "davidtay456",
		createdAt: adjustDate(new Date(), -4),
	},
	{
		id: "8",
		fullName: "Emma Martinez",
		email: "emma.martinez@example.com",
		phoneNumber: "+1444555666",
		instance: "Art Academy",
		password: "emmam789",
		createdAt: adjustDate(new Date(), 5),
	},
	{
		id: "9",
		fullName: "James Anderson",
		email: "james.anderson@example.com",
		phoneNumber: "+1666777888",
		instance: "Medical University",
		password: "jamesand123",
		createdAt: adjustDate(new Date(), 9),
	},
	{
		id: "10",
		fullName: "Olivia Garcia",
		email: "olivia.garcia@example.com",
		phoneNumber: "+1888999000",
		instance: "Science Institute",
		password: "oliviag2023",
		createdAt: adjustDate(new Date(), 2),
	},
	{
		id: "11",
		fullName: "Ethan Wright",
		email: "ethan.wright@example.com",
		phoneNumber: "+1333444555",
		instance: "Polytechnic Institute",
		password: "ethanw567",
		createdAt: adjustDate(new Date(), -2),
	},
	{
		id: "12",
		fullName: "Sophia Lee",
		email: "sophia.lee@example.com",
		phoneNumber: "+1777666555",
		instance: "Language School",
		password: "sophial789",
		createdAt: adjustDate(new Date(), 5),
	},
	{
		id: "13",
		fullName: "Daniel Kim",
		email: "daniel.kim@example.com",
		phoneNumber: "+1222111333",
		instance: "Music Conservatory",
		password: "danielk234",
		createdAt: adjustDate(new Date(), 10),
	},
	{
		id: "14",
		fullName: "Ava Patel",
		email: "ava.patel@example.com",
		phoneNumber: "+1555444333",
		instance: "Fashion Institute",
		password: "avap678",
		createdAt: adjustDate(new Date(), 11),
	},
	{
		id: "15",
		fullName: "William Chen",
		email: "william.chen@example.com",
		phoneNumber: "+1999000111",
		instance: "Law School",
		password: "williamc901",
		createdAt: adjustDate(new Date(), 12),
	},
	{
		id: "16",
		fullName: "Mia Rodriguez",
		email: "mia.rodriguez@example.com",
		phoneNumber: "+1444333222",
		instance: "Culinary Academy",
		password: "miar345",
		createdAt: adjustDate(new Date(), 13),
	},
	{
		id: "17",
		fullName: "Benjamin Davis",
		email: "benjamin.davis@example.com",
		phoneNumber: "+1666555444",
		instance: "Sports University",
		password: "benjamind678",
		createdAt: adjustDate(new Date(), 7),
	},
	{
		id: "18",
		fullName: "Chloe Wilson",
		email: "chloe.wilson@example.com",
		phoneNumber: "+1888777666",
		instance: "Environmental Studies College",
		password: "chloew901",
		createdAt: adjustDate(new Date(), 3),
	},
	{
		id: "19",
		fullName: "Lucas Thompson",
		email: "lucas.thompson@example.com",
		phoneNumber: "+1222333444",
		instance: "Robotics Institute",
		password: "lucast234",
		createdAt: adjustDate(new Date(), 5),
	},
	{
		id: "20",
		fullName: "Isabella Nguyen",
		email: "isabella.nguyen@example.com",
		phoneNumber: "+1777888999",
		instance: "Design School",
		password: "isabellan567",
		createdAt: adjustDate(new Date(), 13),
	},
];

export const studentSchema = z
	.object({
		id: z.string(),
		fullName: z.string(),
		email: z.string(),
		phoneNumber: z.string(),
		instance: z.string(),
		password: z.string(),
		reTypePassword: z.string(),
		createdAt: z.date(),
	})
	.refine((data) => data.password === data.reTypePassword, {
		message: "Passwords do not match",
		path: ["reTypePassword"],
	});
